// Code generated by "enumer -type ClientCode -trimprefix Client -output client_code_gen.go"; DO NOT EDIT.

package proto

import (
	"fmt"
	"strings"
)

const _ClientCodeName = "HelloQueryDataCancelPing"

var _ClientCodeIndex = [...]uint8{0, 5, 10, 14, 20, 24}

const _ClientCodeLowerName = "helloquerydatacancelping"

func (i ClientCode) String() string {
	if i >= ClientCode(len(_ClientCodeIndex)-1) {
		return fmt.Sprintf("ClientCode(%d)", i)
	}
	return _ClientCodeName[_ClientCodeIndex[i]:_ClientCodeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ClientCodeNoOp() {
	var x [1]struct{}
	_ = x[ClientHello-(0)]
	_ = x[ClientQuery-(1)]
	_ = x[ClientData-(2)]
	_ = x[ClientCancel-(3)]
	_ = x[ClientPing-(4)]
}

var _ClientCodeValues = []ClientCode{ClientHello, ClientQuery, ClientData, ClientCancel, ClientPing}

var _ClientCodeNameToValueMap = map[string]ClientCode{
	_ClientCodeName[0:5]:        ClientHello,
	_ClientCodeLowerName[0:5]:   ClientHello,
	_ClientCodeName[5:10]:       ClientQuery,
	_ClientCodeLowerName[5:10]:  ClientQuery,
	_ClientCodeName[10:14]:      ClientData,
	_ClientCodeLowerName[10:14]: ClientData,
	_ClientCodeName[14:20]:      ClientCancel,
	_ClientCodeLowerName[14:20]: ClientCancel,
	_ClientCodeName[20:24]:      ClientPing,
	_ClientCodeLowerName[20:24]: ClientPing,
}

var _ClientCodeNames = []string{
	_ClientCodeName[0:5],
	_ClientCodeName[5:10],
	_ClientCodeName[10:14],
	_ClientCodeName[14:20],
	_ClientCodeName[20:24],
}

// ClientCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ClientCodeString(s string) (ClientCode, error) {
	if val, ok := _ClientCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ClientCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ClientCode values", s)
}

// ClientCodeValues returns all values of the enum
func ClientCodeValues() []ClientCode {
	return _ClientCodeValues
}

// ClientCodeStrings returns a slice of all String values of the enum
func ClientCodeStrings() []string {
	strs := make([]string, len(_ClientCodeNames))
	copy(strs, _ClientCodeNames)
	return strs
}

// IsAClientCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ClientCode) IsAClientCode() bool {
	for _, v := range _ClientCodeValues {
		if i == v {
			return true
		}
	}
	return false
}
