// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

import (
	"github.com/go-faster/errors"
)

// ColInt64 represents Int64 column.
type ColInt64 []int64

// Compile-time assertions for ColInt64.
var (
	_ Input  = ColInt64{}
	_ Result = (*ColInt64)(nil)
)

// Type returns ColumnType of Int64.
func (ColInt64) Type() ColumnType {
	return ColumnTypeInt64
}

// Rows returns count of rows in column.
func (c ColInt64) Rows() int {
	return len(c)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColInt64) Reset() {
	*c = (*c)[:0]
}

// EncodeColumn encodes Int64 rows to *Buffer.
func (c ColInt64) EncodeColumn(b *Buffer) {
	for _, v := range c {
		b.PutInt64(v)
	}
}

// DecodeColumn decodes Int64 rows from *Reader.
func (c *ColInt64) DecodeColumn(r *Reader, rows int) error {
	const size = 64 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}
	v := *c
	for i := 0; i < len(data); i += size {
		v = append(v,
			int64(bin.Uint64(data[i:i+size])),
		)
	}
	*c = v
	return nil
}
