// Code generated by ch-gen-int, DO NOT EDIT.

package proto

import "github.com/go-faster/errors"

type ColumnInt8 []int8

func (ColumnInt8) Type() ColumnType { return ColumnTypeInt8 }
func (c ColumnInt8) Rows() int      { return len(c) }
func (c *ColumnInt8) Reset()        { *c = (*c)[:0] }

func (c ColumnInt8) EncodeColumn(b *Buffer) {
	for _, v := range c {
		b.PutInt8(v)
	}
}

func (c *ColumnInt8) DecodeColumn(r *Reader, rows int) error {
	const size = 8 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}

	v := *c
	for i := 0; i < len(data); i += size {
		v = append(v,
			int8(data[i]),
		)
	}
	*c = v

	return nil
}
