// Code generated by ch-gen-int, DO NOT EDIT.

package proto

import "github.com/go-faster/errors"

type ColumnUInt16 []uint16

func (ColumnUInt16) Type() ColumnType { return ColumnTypeUInt16 }
func (c ColumnUInt16) Rows() int      { return len(c) }
func (c *ColumnUInt16) Reset()        { *c = (*c)[:0] }

func (c ColumnUInt16) EncodeColumn(b *Buffer) {
	for _, v := range c {
		b.PutUInt16(v)
	}
}

func (c *ColumnUInt16) DecodeColumn(r *Reader, rows int) error {
	const size = 16 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}

	v := *c
	for i := 0; i < len(data); i += size {
		v = append(v,
			bin.Uint16(data[i:i+size]),
		)
	}
	*c = v

	return nil
}
