// Code generated by ch-gen-int, DO NOT EDIT.

package proto

import "github.com/go-faster/errors"

type ColumnInt32 []int32

func (ColumnInt32) Type() ColumnType { return ColumnTypeInt32 }
func (c ColumnInt32) Rows() int      { return len(c) }
func (c *ColumnInt32) Reset()        { *c = (*c)[:0] }

func (c ColumnInt32) EncodeColumn(b *Buffer) {
	for _, v := range c {
		b.PutInt32(v)
	}
}

func (c *ColumnInt32) DecodeColumn(r *Reader, rows int) error {
	const size = 32 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}

	v := *c
	for i := 0; i < len(data); i += size {
		v = append(v,
			int32(bin.Uint32(data[i:i+size])),
		)
	}
	*c = v

	return nil
}
