// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

import "github.com/go-faster/errors"

type ColumnUInt8 []uint8

func (ColumnUInt8) Type() ColumnType { return ColumnTypeUInt8 }
func (c ColumnUInt8) Rows() int      { return len(c) }
func (c *ColumnUInt8) Reset()        { *c = (*c)[:0] }

func (c ColumnUInt8) EncodeColumn(b *Buffer) {
	for _, v := range c {
		b.PutUInt8(v)
	}
}

func (c *ColumnUInt8) DecodeColumn(r *Reader, rows int) error {
	const size = 8 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}

	*c = append(*c, data...)

	return nil
}
