// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

import (
	"github.com/go-faster/errors"
)

// ColInt16 represents Int16 column.
type ColInt16 []int16

// Compile-time assertions for ColInt16.
var (
	_ Input  = ColInt16{}
	_ Result = (*ColInt16)(nil)
)

// Type returns ColumnType of Int16.
func (ColInt16) Type() ColumnType {
	return ColumnTypeInt16
}

// Rows returns count of rows in column.
func (c ColInt16) Rows() int {
	return len(c)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColInt16) Reset() {
	*c = (*c)[:0]
}

// EncodeColumn encodes Int16 rows to *Buffer.
func (c ColInt16) EncodeColumn(b *Buffer) {
	for _, v := range c {
		b.PutInt16(v)
	}
}

// DecodeColumn decodes Int16 rows from *Reader.
func (c *ColInt16) DecodeColumn(r *Reader, rows int) error {
	const size = 16 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}
	v := *c
	for i := 0; i < len(data); i += size {
		v = append(v,
			int16(bin.Uint16(data[i:i+size])),
		)
	}
	*c = v
	return nil
}
