// Code generated by ch-gen-int, DO NOT EDIT.

package proto

import "github.com/go-faster/errors"

type ColumnUInt32 []uint32

func (ColumnUInt32) Type() ColumnType { return ColumnTypeUInt32 }
func (c ColumnUInt32) Rows() int      { return len(c) }
func (c *ColumnUInt32) Reset()        { *c = (*c)[:0] }

func (c ColumnUInt32) EncodeColumn(b *Buffer) {
	for _, v := range c {
		b.PutUInt32(v)
	}
}

func (c *ColumnUInt32) DecodeColumn(r *Reader, rows int) error {
	const size = 32 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}

	v := *c
	for i := 0; i < len(data); i += size {
		v = append(v,
			bin.Uint32(data[i:i+size]),
		)
	}
	*c = v

	return nil
}
