// Code generated by ch-gen-int, DO NOT EDIT.

package proto

import "github.com/go-faster/errors"

type ColumnInt16 []int16

func (ColumnInt16) Type() ColumnType { return ColumnTypeInt16 }
func (c ColumnInt16) Rows() int      { return len(c) }
func (c *ColumnInt16) Reset()        { *c = (*c)[:0] }

func (c ColumnInt16) EncodeColumn(b *Buffer) {
	for _, v := range c {
		b.PutInt16(v)
	}
}

func (c *ColumnInt16) DecodeColumn(r *Reader, rows int) error {
	const size = 16 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}

	v := *c
	for i := 0; i < len(data); i += size {
		v = append(v,
			int16(bin.Uint16(data[i:i+size])),
		)
	}
	*c = v

	return nil
}
