// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

import "github.com/go-faster/errors"

type ColumnInt64 []int64

func (ColumnInt64) Type() ColumnType { return ColumnTypeInt64 }
func (c ColumnInt64) Rows() int      { return len(c) }
func (c *ColumnInt64) Reset()        { *c = (*c)[:0] }

func (c ColumnInt64) EncodeColumn(b *Buffer) {
	for _, v := range c {
		b.PutInt64(v)
	}
}

func (c *ColumnInt64) DecodeColumn(r *Reader, rows int) error {
	const size = 64 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}

	v := *c
	for i := 0; i < len(data); i += size {
		v = append(v,
			int64(bin.Uint64(data[i:i+size])),
		)
	}
	*c = v

	return nil
}
