{{- /*gotype: github.com/go-faster/ch/proto/cmd/ch-gen-col.Variants*/ -}}
// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto


// inferNumeric infers t as numeric type, otherwise returns false.
func (c *ColAuto) inferNumeric(t ColumnType) bool {
	switch t {
  {{- range . }}
	case {{ .ColumnType }}:
		c.Data = new({{ .Type }})
  {{- end }}
	default:
		return false
	}
	return true
}
