// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

// inferNumeric infers t as numeric type, otherwise returns false.
func (c *ColAuto) inferNumeric(t ColumnType) bool {
	switch t {
	case ColumnTypeFloat32:
		c.Data = new(ColFloat32)
	case ColumnTypeFloat64:
		c.Data = new(ColFloat64)
	case ColumnTypeIPv4:
		c.Data = new(ColIPv4)
	case ColumnTypeIPv6:
		c.Data = new(ColIPv6)
	case ColumnTypeDate:
		c.Data = new(ColDate)
	case ColumnTypeDate32:
		c.Data = new(ColDate32)
	case ColumnTypeInt8:
		c.Data = new(ColInt8)
	case ColumnTypeUInt8:
		c.Data = new(ColUInt8)
	case ColumnTypeInt16:
		c.Data = new(ColInt16)
	case ColumnTypeUInt16:
		c.Data = new(ColUInt16)
	case ColumnTypeInt32:
		c.Data = new(ColInt32)
	case ColumnTypeUInt32:
		c.Data = new(ColUInt32)
	case ColumnTypeInt64:
		c.Data = new(ColInt64)
	case ColumnTypeUInt64:
		c.Data = new(ColUInt64)
	case ColumnTypeInt128:
		c.Data = new(ColInt128)
	case ColumnTypeUInt128:
		c.Data = new(ColUInt128)
	case ColumnTypeInt256:
		c.Data = new(ColInt256)
	case ColumnTypeUInt256:
		c.Data = new(ColUInt256)
	default:
		return false
	}
	return true
}
