// Code generated by ./cmd/ch-gen-col, DO NOT EDIT.

package proto

// ColInt64 represents Int64 column.
type ColInt64 []int64

// Compile-time assertions for ColInt64.
var (
	_ ColInput  = ColInt64{}
	_ ColResult = (*ColInt64)(nil)
	_ Column    = (*ColInt64)(nil)
)

// Type returns ColumnType of Int64.
func (ColInt64) Type() ColumnType {
	return ColumnTypeInt64
}

// Rows returns count of rows in column.
func (c ColInt64) Rows() int {
	return len(c)
}

// Row returns i-th row of column.
func (c ColInt64) Row(i int) int64 {
	return c[i]
}

// Append int64 to column.
func (c *ColInt64) Append(v int64) {
	*c = append(*c, v)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColInt64) Reset() {
	*c = (*c)[:0]
}

// LowCardinality returns LowCardinality for Int64 .
func (c *ColInt64) LowCardinality() *ColLowCardinalityOf[int64] {
	return &ColLowCardinalityOf[int64]{
		index: c,
	}
}

// Array is helper that creates Array of int64.
func (c *ColInt64) Array() *ColArrOf[int64] {
	return &ColArrOf[int64]{
		Data: c,
	}
}

// NewArrInt64 returns new Array(Int64).
func NewArrInt64() *ColArrOf[int64] {
	return &ColArrOf[int64]{
		Data: new(ColInt64),
	}
}
