//go:build !(amd64 || arm64 || riscv64) || purego

// Code generated by ./cmd/ch-gen-col, DO NOT EDIT.

package proto

import (
	"encoding/binary"

	"github.com/go-faster/errors"
)

var _ = binary.LittleEndian // clickHouse uses LittleEndian

// DecodeColumn decodes Time32 rows from *Reader.
func (c *ColTime32) DecodeColumn(r *Reader, rows int) error {
	if rows == 0 {
		return nil
	}
	const size = 32 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}
	// Move bound check out of loop.
	//
	// See https://github.com/golang/go/issues/30945.
	_ = data[len(data)-size]
	c.Data = c.Data[:0]
	for i := 0; i <= len(data)-size; i += size {
		c.Data = append(c.Data,
			Time32(binary.LittleEndian.Uint32(data[i:i+size])),
		)
	}
	return nil
}

// EncodeColumn encodes Time32 rows to *Buffer.
func (c ColTime32) EncodeColumn(b *Buffer) {
	if len(c.Data) == 0 {
		return
	}
	const size = 32 / 8
	offset := len(b.Buf)
	b.Buf = append(b.Buf, make([]byte, size*len(c.Data))...)
	for _, vv := range c.Data {
		binary.LittleEndian.PutUint32(
			b.Buf[offset:offset+size],
			uint32(vv),
		)
		offset += size
	}
}

func (c ColTime32) WriteColumn(w *Writer) {
	w.ChainBuffer(c.EncodeColumn)
}
