//go:build ignore

// Code generated by ./cmd/ch-gen-col, DO NOT EDIT.

package proto

import (
	"encoding/binary"

	"github.com/go-faster/errors"
)

var _ = binary.LittleEndian // clickHouse uses LittleEndian

// DecodeColumn decodes Time32 rows from *Reader.
func (c *ColTime32) DecodeColumn(r *Reader, rows int) error {
	if rows == 0 {
		return nil
	}
	const size = 32 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}
	v := *c
	// Move bound check out of loop.
	//
	// See https://github.com/golang/go/issues/30945.
	_ = data[len(data)-size]
	for i := 0; i <= len(data)-size; i += size {
		v = append(v,
			Time32(binary.LittleEndian.Uint32(data[i:i+size])),
		)
	}
	*c = v
	return nil
}

// EncodeColumn encodes Time32 rows to *Buffer.
func (c ColTime32) EncodeColumn(b *Buffer) {
	v := c
	if len(v) == 0 {
		return
	}
	offset := len(b.Buf)
	const size = 32 / 8
	b.Buf = append(b.Buf, make([]byte, size*len(v))...)
	s := b.Buf[offset:]
	for i, v := range v {
		binary.LittleEndian.PutUint32(
			s[i*size:],
			uint32(v),
		)
	}
}

func (c ColTime32) WriteColumn(w *Writer) {
	w.ChainBuffer(c.EncodeColumn)
}
