//go:build ignore

// Code generated by ./cmd/ch-gen-col, DO NOT EDIT.

package proto

// ColTime64 represents Time64 column.
type ColTime64 []Time64

// Compile-time assertions for ColTime64.
var (
	_ ColInput  = ColTime64{}
	_ ColResult = (*ColTime64)(nil)
	_ Column    = (*ColTime64)(nil)
)

// Rows returns count of rows in column.
func (c ColTime64) Rows() int {
	return len(c)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColTime64) Reset() {
	*c = (*c)[:0]
}

// Type returns ColumnType of Time64.
func (ColTime64) Type() ColumnType {
	return ColumnTypeTime64
}
