//go:build ignore

// Code generated by ./cmd/ch-gen-col, DO NOT EDIT.

package proto

// ColTime32 represents Time32 column.
type ColTime32 []Time32

// Compile-time assertions for ColTime32.
var (
	_ ColInput  = ColTime32{}
	_ ColResult = (*ColTime32)(nil)
	_ Column    = (*ColTime32)(nil)
)

// Rows returns count of rows in column.
func (c ColTime32) Rows() int {
	return len(c)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColTime32) Reset() {
	*c = (*c)[:0]
}

// Type returns ColumnType of Time32.
func (ColTime32) Type() ColumnType {
	return ColumnTypeTime32
}
