// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

import (
	"encoding/binary"
)

var _ = binary.LittleEndian // clickHouse uses LittleEndian

// ColIPv6 represents IPv6 column.
type ColIPv6 []IPv6

// Compile-time assertions for ColIPv6.
var (
	_ ColInput  = ColIPv6{}
	_ ColResult = (*ColIPv6)(nil)
	_ Column    = (*ColIPv6)(nil)
)

// Type returns ColumnType of IPv6.
func (ColIPv6) Type() ColumnType {
	return ColumnTypeIPv6
}

// Rows returns count of rows in column.
func (c ColIPv6) Rows() int {
	return len(c)
}

// Row returns i-th row of column.
func (c ColIPv6) Row(i int) IPv6 {
	return c[i]
}

// Append IPv6 to column.
func (c *ColIPv6) Append(v IPv6) {
	*c = append(*c, v)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColIPv6) Reset() {
	*c = (*c)[:0]
}

// NewArrIPv6 returns new Array(IPv6).
func NewArrIPv6() *ColArr {
	return &ColArr{
		Data: new(ColIPv6),
	}
}

// AppendIPv6 appends slice of IPv6 to Array(IPv6).
func (c *ColArr) AppendIPv6(data []IPv6) {
	d := c.Data.(*ColIPv6)
	*d = append(*d, data...)
	c.Offsets = append(c.Offsets, uint64(len(*d)))
}
