// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

import (
	"encoding/binary"
	"github.com/go-faster/errors"
)

// ClickHouse uses LittleEndian.
var _ = binary.LittleEndian

// ColInt16 represents Int16 column.
type ColInt16 []int16

// Compile-time assertions for ColInt16.
var (
	_ ColInput  = ColInt16{}
	_ ColResult = (*ColInt16)(nil)
	_ Column    = (*ColInt16)(nil)
)

// Type returns ColumnType of Int16.
func (ColInt16) Type() ColumnType {
	return ColumnTypeInt16
}

// Rows returns count of rows in column.
func (c ColInt16) Rows() int {
	return len(c)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColInt16) Reset() {
	*c = (*c)[:0]
}

// NewArrInt16 returns new Array(Int16).
func NewArrInt16() *ColArr {
	return &ColArr{
		Data: new(ColInt16),
	}
}

// AppendInt16 appends slice of int16 to Array(Int16).
func (c *ColArr) AppendInt16(data []int16) {
	d := c.Data.(*ColInt16)
	*d = append(*d, data...)
	c.Offsets = append(c.Offsets, uint64(len(*d)))
}

// EncodeColumn encodes Int16 rows to *Buffer.
func (c ColInt16) EncodeColumn(b *Buffer) {
	const size = 16 / 8
	offset := len(b.Buf)
	b.Buf = append(b.Buf, make([]byte, size*len(c))...)
	for _, v := range c {
		binary.LittleEndian.PutUint16(
			b.Buf[offset:offset+size],
			uint16(v),
		)
		offset += size
	}
}

// DecodeColumn decodes Int16 rows from *Reader.
func (c *ColInt16) DecodeColumn(r *Reader, rows int) error {
	if rows == 0 {
		return nil
	}
	const size = 16 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}
	v := *c
	// Move bound check out of loop.
	//
	// See https://github.com/golang/go/issues/30945.
	_ = data[len(data)-size]
	for i := 0; i <= len(data)-size; i += size {
		v = append(v,
			int16(binary.LittleEndian.Uint16(data[i:i+size])),
		)
	}
	*c = v
	return nil
}
