// Code generated by ./cmd/ch-gen-col, DO NOT EDIT.

package proto

// ColUInt64 represents UInt64 column.
type ColUInt64 []uint64

// Compile-time assertions for ColUInt64.
var (
	_ ColInput  = ColUInt64{}
	_ ColResult = (*ColUInt64)(nil)
	_ Column    = (*ColUInt64)(nil)
)

// Type returns ColumnType of UInt64.
func (ColUInt64) Type() ColumnType {
	return ColumnTypeUInt64
}

// Rows returns count of rows in column.
func (c ColUInt64) Rows() int {
	return len(c)
}

// Row returns i-th row of column.
func (c ColUInt64) Row(i int) uint64 {
	return c[i]
}

// Append uint64 to column.
func (c *ColUInt64) Append(v uint64) {
	*c = append(*c, v)
}

// AppendArr appends slice of uint64 to column.
func (c *ColUInt64) AppendArr(v []uint64) {
	*c = append(*c, v...)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColUInt64) Reset() {
	*c = (*c)[:0]
}

// LowCardinality returns LowCardinality for UInt64 .
func (c *ColUInt64) LowCardinality() *ColLowCardinalityOf[uint64] {
	return &ColLowCardinalityOf[uint64]{
		index: c,
	}
}

// Array is helper that creates Array of uint64.
func (c *ColUInt64) Array() *ColArrOf[uint64] {
	return &ColArrOf[uint64]{
		Data: c,
	}
}

// NewArrUInt64 returns new Array(UInt64).
func NewArrUInt64() *ColArr {
	return &ColArr{
		Data: new(ColUInt64),
	}
}

// AppendUInt64 appends slice of uint64 to Array(UInt64).
func (c *ColArr) AppendUInt64(data []uint64) {
	d := c.Data.(*ColUInt64)
	*d = append(*d, data...)
	c.Offsets = append(c.Offsets, uint64(len(*d)))
}
