// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

import (
	"github.com/go-faster/errors"
)

// ColUInt64 represents UInt64 column.
type ColUInt64 []uint64

// Compile-time assertions for ColUInt64.
var (
	_ Input  = ColUInt64{}
	_ Result = (*ColUInt64)(nil)
	_ Column = (*ColUInt64)(nil)
)

// Type returns ColumnType of UInt64.
func (ColUInt64) Type() ColumnType {
	return ColumnTypeUInt64
}

// Rows returns count of rows in column.
func (c ColUInt64) Rows() int {
	return len(c)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColUInt64) Reset() {
	*c = (*c)[:0]
}

// NewArrUInt64 returns new Array(UInt64).
func NewArrUInt64() *ColArr {
	return &ColArr{
		Data: new(ColUInt64),
	}
}

// AppendUInt64 appends slice of uint64 to Array(UInt64).
func (c *ColArr) AppendUInt64(data []uint64) {
	d := c.Data.(*ColUInt64)
	*d = append(*d, data...)
	c.Offsets = append(c.Offsets, uint64(len(*d)))
}

// EncodeColumn encodes UInt64 rows to *Buffer.
func (c ColUInt64) EncodeColumn(b *Buffer) {
	const size = 64 / 8
	offset := len(b.Buf)
	b.Buf = append(b.Buf, make([]byte, size*len(c))...)
	for _, v := range c {
		bin.PutUint64(
			b.Buf[offset:offset+size],
			v,
		)
		offset += size
	}
}

// DecodeColumn decodes UInt64 rows from *Reader.
func (c *ColUInt64) DecodeColumn(r *Reader, rows int) error {
	const size = 64 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}
	v := *c
	for i := 0; i < len(data); i += size {
		v = append(v,
			bin.Uint64(data[i:i+size]),
		)
	}
	*c = v
	return nil
}
