// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

import (
	"encoding/binary"
	"github.com/go-faster/errors"
)

// ClickHouse uses LittleEndian.
var _ = binary.LittleEndian

// ColDecimal32 represents Decimal32 column.
type ColDecimal32 []Decimal32

// Compile-time assertions for ColDecimal32.
var (
	_ ColInput  = ColDecimal32{}
	_ ColResult = (*ColDecimal32)(nil)
	_ Column    = (*ColDecimal32)(nil)
)

// Type returns ColumnType of Decimal32.
func (ColDecimal32) Type() ColumnType {
	return ColumnTypeDecimal32
}

// Rows returns count of rows in column.
func (c ColDecimal32) Rows() int {
	return len(c)
}

// Row returns i-th row of column.
func (c ColDecimal32) Row(i int) Decimal32 {
	return c[i]
}

// Append Decimal32 to column.
func (c *ColDecimal32) Append(v Decimal32) {
	*c = append(*c, v)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColDecimal32) Reset() {
	*c = (*c)[:0]
}

// NewArrDecimal32 returns new Array(Decimal32).
func NewArrDecimal32() *ColArr {
	return &ColArr{
		Data: new(ColDecimal32),
	}
}

// AppendDecimal32 appends slice of Decimal32 to Array(Decimal32).
func (c *ColArr) AppendDecimal32(data []Decimal32) {
	d := c.Data.(*ColDecimal32)
	*d = append(*d, data...)
	c.Offsets = append(c.Offsets, uint64(len(*d)))
}

// EncodeColumn encodes Decimal32 rows to *Buffer.
func (c ColDecimal32) EncodeColumn(b *Buffer) {
	const size = 32 / 8
	offset := len(b.Buf)
	b.Buf = append(b.Buf, make([]byte, size*len(c))...)
	for _, v := range c {
		binary.LittleEndian.PutUint32(
			b.Buf[offset:offset+size],
			uint32(v),
		)
		offset += size
	}
}

// DecodeColumn decodes Decimal32 rows from *Reader.
func (c *ColDecimal32) DecodeColumn(r *Reader, rows int) error {
	if rows == 0 {
		return nil
	}
	const size = 32 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}
	v := *c
	// Move bound check out of loop.
	//
	// See https://github.com/golang/go/issues/30945.
	_ = data[len(data)-size]
	for i := 0; i <= len(data)-size; i += size {
		v = append(v,
			Decimal32(binary.LittleEndian.Uint32(data[i:i+size])),
		)
	}
	*c = v
	return nil
}
