name: x

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  # See https://github.com/go-faster/x
  # Includes test, coverage, golangci-lint, commit lint, generate checks
  ci:
    uses: go-faster/x/.github/workflows/ci.yml@main
